name : Cypress Tests

on: 
  workflow_dispatch:
   
jobs:
  cypress-electron-tests: 
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.21.0-chrome-141.0.7390.107-1-ff-144.0-edge-141.0.3537.92-1
      options: --user 1001
    steps:
       - name: Get code
         uses: actions/checkout@v6.0.0

       - name: Install dependencies
         run: yarn install

       - name: Run E2E tests
         run: node runner-electron.js
    env: 
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }}
      
  cypress-chrome-tests: 
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.21.0-chrome-141.0.7390.107-1-ff-144.0-edge-141.0.3537.92-1
      options: --user 1001
    steps:
       - name: Get code
         uses: actions/checkout@v6.0.0

       - name: Install dependencies
         run: yarn install

       - name: Run E2E tests
         run: node runner-chrome.js
    env: 
      TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }}
      
  cypress-firefox-tests: 
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.21.0-chrome-141.0.7390.107-1-ff-144.0-edge-141.0.3537.92-1
      options: --user 1001
    steps:
       - name: Get code
         uses: actions/checkout@v6.0.0

       - name: Install dependencies
         run: yarn install

       - name: Run E2E tests
         run: node runner-firefox.js
    env: 
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX }}
  
