name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs: 
      spec:
         description: Run by cypress command line
         default: cypress/e2e/*
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.21.0-chrome-141.0.7390.107-1-ff-144.0-edge-141.0.3537.92-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 73dfd449-02f1-4db9-9ee1-e85237f6dd13
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.21.0-chrome-141.0.7390.107-1-ff-144.0-edge-141.0.3537.92-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 73dfd449-02f1-4db9-9ee1-e85237f6dd13
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-firefox:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.21.0-chrome-141.0.7390.107-1-ff-144.0-edge-141.0.3537.92-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 73dfd449-02f1-4db9-9ee1-e85237f6dd13
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
